# Generated by Django 2.2.6 on 2019-10-09 10:51

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='text'),
        ),
    ]
