# Generated by Django 2.2.6 on 2019-10-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191021_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read',
            field=models.BooleanField(default=False, verbose_name='read'),
        ),
    ]
