# Generated by Django 2.2.6 on 2019-10-09 11:25

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=martor.models.MartorField(blank=True, verbose_name='text'),
        ),
    ]
