# Generated by Django 2.2.6 on 2019-10-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='founder',
            field=models.BooleanField(default=False, verbose_name='founder'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
    ]
