# Generated by Django 2.2.6 on 2019-10-21 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_auto_20191021_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Message',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
