# Generated by Django 2.2.6 on 2019-10-21 20:51

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_auto_20191021_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='date_time')),
                ('name', models.CharField(max_length=124, verbose_name='name')),
                ('email', models.CharField(max_length=124, verbose_name='email')),
                ('comment', models.TextField(verbose_name='comment')),
                ('parent_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post',
                                                  verbose_name='parent_post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-date_time'],
            },
        ),
    ]
